version: 2.0
jobs:
  build:
    machine: true
        
    steps:
      - checkout
      - run:
          name: Install requests
          command: |
            pip install -r requirements.txt
      - run:
          name: Mobile app
          command: |
            git clone https://github.com/qxf2/bitcoin-info.git
            cd ./bitcoin-info/app
            export app_path=`pwd`
            echo $app_path
            ls -al
            chmod 777 *.apk
            #export $app_path
      - run:
          name: Decrypt remote_credentials_enc.py using openssl
          command: |
            openssl aes-256-cbc -d -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY     
      - run:
          name: Run the API and Selenium tests only (Ignoring to run mobile test as we are not yet set to run mobile test on server)
          command: |
            echo $app_path   
            #echo "path" > /home/circleci/project/bitcoin-info/app/           
            #py.test -s -k mobile -M Y --remote_project_name Qxf2_Selenium_POM --remote_build_name Selenium_Tutorial
            #py.test -s -v -k mobile -N "/home/circleci/project/bitcoin-info/app" -M Y --remote_project_name Qxf2_Selenium_POM --remote_build_name Selenium_Tutorial --junitxml=test-reports/junit.xml --tb=native                      
                      

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file